tui

diff --git a/packages/k8s/cocmd.yaml b/packages/k8s/cocmd.yaml
--- a/packages/k8s/cocmd.yaml
+++ b/packages/k8s/cocmd.yaml
@@ -1,32 +1,147 @@
 name: k8s
 aliases: |
     alias k='kubectl'
+    alias kl='kubectl logs'
+    alias kexec='kubectl exec -it'
+    alias kpf='kubectl port-forward'
+    alias kaci='kubectl auth can-i'
+    alias kat='kubectl attach'
+    alias kapir='kubectl api-resources'
+    alias kapiv='kubectl api-versions'
+
+    # get
+    alias kg='kubectl get'
+    alias kgns='kubectl get ns'
     alias kgp='kubectl get pods'
-    alias kgs='kubectl get svc'
-    alias kgn='kubectl get nodes'
-    alias kgc='kubectl get componentstatuses'
+    alias kgs='kubectl get secrets'
+    alias kgd='kubectl get deploy'
+    alias kgrs='kubectl get rs'
+    alias kgss='kubectl get sts'
+    alias kgds='kubectl get ds'
+    alias kgcm='kubectl get configmap'
+    alias kgcj='kubectl get cronjob'
+    alias kgj='kubectl get job'
+    alias kgsvc='kubectl get svc -o wide'
+    alias kgn='kubectl get no -o wide'
+    alias kgr='kubectl get roles'
+    alias kgrb='kubectl get rolebindings'
+    alias kgcr='kubectl get clusterroles'
+    alias kgrb='kubectl get clusterrolebindings'
+    alias kgsa='kubectl get sa'
+    alias kgnet='kubectl get netpol'
+
+    # edit
+    alias ke='kubectl edit'
+    alias kens='kubectl edit ns'
+    alias kes='kubectl edit secrets'
+    alias ked='kubectl edit deploy'
+    alias kers='kubectl edit rs'
+    alias kess='kubectl edit sts'
+    alias keds='kubectl edit ds'
+    alias kesvc='kubectl edit svc'
+    alias kecm='kubectl edit cm'
+    alias kecj='kubectl edit cj'
+    alias ker='kubectl edit roles'
+    alias kerb='kubectl edit rolebindings'
+    alias kecr='kubectl edit clusterroles'
+    alias kerb='kubectl edit clusterrolebindings'
+    alias kesa='kubectl edit sa'
+    alias kenet='kubectl edit netpol'
+
+    # describe
     alias kd='kubectl describe'
-    alias krm='kubectl delete'
-    alias kex='kubectl exec -it'
-    alias klo='kubectl logs'
-    alias kaf='kubectl apply -f'
-    alias kdf='kubectl delete -f'
-    alias kctx='kubectx'
-    alias kns='kubens'
+    alias kdns='kubectl describe ns'
+    alias kdp='kubectl describe pod'
+    alias kds='kubectl describe secrets'
+    alias kdd='kubectl describe deploy'
+    alias kdrs='kubectl describe rs'
+    alias kdss='kubectl describe sts'
+    alias kdds='kubectl describe ds'
+    alias kdsvc='kubectl describe svc'
+    alias kdcm='kubectl describe cm'
+    alias kdcj='kubectl describe cj'
+    alias kdj='kubectl describe job'
+    alias kdsa='kubectl describe sa'
+    alias kdr='kubectl describe roles'
+    alias kdrb='kubectl describe rolebindings'
+    alias kdcr='kubectl describe clusterroles'
+    alias kdcrb='kubectl describe clusterrolebindings'
+    alias kdnet='kubectl describe netpol'
+
+    # delete
+    alias kdel='kubectl delete'
+    alias kdelns='kubectl delete ns'
+    alias kdels='kubectl delete secrets'
+    alias kdelp='kubectl delete po'
+    alias kdeld='kubectl delete deployment'
+    alias kdelrs='kubectl delete rs'
+    alias kdelss='kubectl delete sts'
+    alias kdelds='kubectl delete ds'
+    alias kdelsvc='kubectl delete svc'
+    alias kdelcm='kubectl delete cm'
+    alias kdelcj='kubectl delete cj'
+    alias kdelj='kubectl delete job'
+    alias kdelr='kubectl delete roles'
+    alias kdelrb='kubectl delete rolebindings'
+    alias kdelcr='kubectl delete clusterroles'
+    alias kdelrb='kubectl delete clusterrolebindings'
+    alias kdelsa='kubectl delete sa'
+    alias kdelnet='kubectl delete netpol'
+
+    # mock
+    alias kmock='kubectl create mock -o yaml --dry-run=client'
+    alias kmockns='kubectl create ns mock -o yaml --dry-run=client'
+    alias kmockcm='kubectl create cm mock -o yaml --dry-run=client'
+    alias kmocksa='kubectl create sa mock -o yaml --dry-run=client'
+
+    # config
+    alias kcfg='kubectl config'
+    alias kcfgv='kubectl config view'
+    alias kcfgns='kubectl config set-context --current --namespace'
+    alias kcfgcurrent='kubectl config current-context'
+    alias kcfggc='kubectl config get-contexts'
+    alias kcfgsc='kubectl config set-context'
+    alias kcfguc='kubectl config use-context'
+    alias kcfgv='kubectl config view'
+
+    # Kubescape related
+    alias kssbom='kubectl -n kubescape get sbomspdxv2p3s'
+    alias kssbomf='kubectl -n kubescape get sbomspdxv2p3filtereds'
+    alias kssboms='kubectl -n kubescape get sbomsummaries'
+    alias ksvulns='kubectl -n kubescape get vulnerabilitymanifestsummaries'
+    alias ksvuln='kubectl -n kubescape get vulnerabilitymanifests'
+
+    # Kubescape related with labels
+    alias kssboml='kubectl -n kubescape get sbomspdxv2p3s --show-labels'
+    alias kssbomfl='kubectl -n kubescape get sbomspdxv2p3filtereds --show-labels'
+    alias kssbomsl='kubectl -n kubescape get sbomsummaries --show-labels'
+    alias ksvulnsl='kubectl -n kubescape get vulnerabilitymanifestsummaries --show-labels'
+    alias ksvulnl='kubectl -n kubescape get vulnerabilitymanifests --show-labels'
+
+    alias m='minikube'
+    alias ma='minikube addons'
+    alias ms='minikube service'
+    alias minid='minikube delete'
+    alias minis='minikube start'
+    alias miniv='minikube version'
 automations:
   - name: setup
-    file: ./scripts/setup.yaml
+    file: ./scripts/setup.osx.yaml
+  - name: setup
+    file: ./scripts/setup.linux.yaml
   - name: backup-configmaps
     content:
       description: "Backup all ConfigMaps in a namespace"
+      params: 
+        - name: namespace
+          save: false
+        - name: backup_dir
+          save: false
       steps:
         - content: |
-            #!/bin/bash
-            NAMESPACE=$1
-            BACKUP_DIR=$2
-            mkdir -p $BACKUP_DIR
-            for cm in $(kubectl get configmap -n $NAMESPACE -o name); do
-              kubectl get $cm -n $NAMESPACE -o yaml > $BACKUP_DIR/$(basename $cm).yaml
+            mkdir -p {{backup_dir}}
+            for cm in $(kubectl get configmap -n {{namespace}} -o name); do
+              kubectl get $cm -n {{namespace}} -o yaml > {{backup_dir}}/$(basename $cm).yaml
             done
           description: "This will backup all ConfigMaps in a given namespace to a directory"
           runner: shell
@@ -34,24 +149,75 @@ automations:
   - name: rolling-restart
     content:
       description: "Perform a rolling restart of a Deployment"
+      params: 
+        - name: namespace
+          save: false
+        - name: deployment
+          save: false
       steps:
         - content: |
-            #!/bin/bash
-            DEPLOYMENT_NAME=$1
-            NAMESPACE=$2
-            kubectl rollout restart deployment $DEPLOYMENT_NAME -n $NAMESPACE
+            kubectl rollout restart deployment {{deployment}} -n {{namespace}}
           description: "This will perform a rolling restart of a Deployment in a given namespace"
           runner: shell
           title: "Rolling Restart"
   - name: batch-pod-deletion
     content:
       description: "Batch delete Pods based on a label"
+      params: 
+        - name: namespace
+          save: false
+        - name: label
+          save: false
       steps:
         - content: |
-            #!/bin/bash
-            LABEL_SELECTOR=$1
-            NAMESPACE=$2
-            kubectl get pods -n $NAMESPACE --selector=$LABEL_SELECTOR -o name | xargs -I {} kubectl delete {} -n $NAMESPACE
+            kubectl get pods -n {{namespace}} --selector={{label}} -o name | xargs -I {} kubectl delete {} -n $NAMESPACE
           description: "This will delete all Pods in a given namespace that match a label selector"
           runner: shell
           title: "Batch Pod Deletion"
+  - name: check-pod-restarts
+    content:
+      description: "Check for Pods with restart counts greater than 0"
+      params: 
+        - name: namespace
+          save: false
+        - name: regex
+          save: false
+      steps:
+        - content: |
+            namespace={{namespace}}
+            regex={{regex}}
+
+            # Run the kubectl command and store the result in a variable
+            result=$(kubectl get pods -n {{namespace}} --field-selector=status.phase==Running --sort-by=.metadata.creationTimestamp -o custom-columns="NAME:.metadata.name,RESTARTS:.status.containerStatuses[0].restartCount")
+
+            # Check for errors
+            if [ $? -ne 0 ]; then
+              echo "CMD Err: $result"
+              exit 1
+            fi
+
+            # Initialize an array to store the names of pods with restart count greater than 0
+            pods_with_restart_gt_zero=()
+
+            # Iterate over each line of the result, filter based on restart count, and format the output
+            echo "$result" | while read -r line; do
+              if [ -n "$line" ] && ! [[ $line =~ " 0$" ]] && [[ $line =~ $regex ]]; then
+                
+                pods_with_restart_gt_zero+=("$(echo "$line" | awk '{print $1}')")
+              fi
+            done
+
+            # Exit with failure if any pod has a restart count greater than 0 and print a message
+            if [ ${#pods_with_restart_gt_zero[@]} -gt 0 ]; then
+              echo "Exiting with error: Some pods have a restart count greater than 0."
+              echo "Pods with restart count > 0: ${pods_with_restart_gt_zero[@]}"
+              exit 1
+            else
+              echo "Everything is okay. No pods with restart counts greater than 0 found."
+              exit 0
+            fi
+
+          description: "This will check for Pods with restart counts greater than 0 in a given namespace"
+          runner: shell
+          title: "Check Pod Restarts"
+              
